### ISSUE TITLE
Support Flow static type declaration

### ISSUE THREAD

**Issue by aziz** [bathos/Ecmascript-Sublime#10]
Again looking at on some React project I see a lot of invalid scopes because they've used flow type declarations. I believe it should be easy to add support for it, right?

**Comment by bathos** [comment]
I'm afraid Flow doesn't belong here. Flow isn't an extension of the ES grammar in the same sense as JSX. In the case of JSX, the grammar was carefully designed to ensure it would never conflict with existing ES productions; it is truly a "safe" extension. But Flow isn't simple like that. Though the lines can be blurry, and they don't say it outright in their docs, Flow isn't JS, it's a *different language*, like CoffeeScript. They do acknowledge this in their TOC, though:

> LANGUAGE REFERENCE
> 
> Quick Reference
> Type Annotations
> Variables
> Arrays and Tuples
> Classes
> Objects
> Functions
> Maybe Types
> Destructuring
> Union and Intersection Types
> Type Aliases
> Typeof types
> Operators
> Dynamic Type Tests
> Primitives
> Declarations

That doesn't look like the TOC for a simple proposed extension :)

For a practical example of why we can't do Flow: "declare" is not a reserved word in ES. If I treat as one, I've stopped having 100% of support of ES. Flow should have its own syntax definition, like any other language.

**Comment by aziz** [comment]
Fair enough!
