### ISSUE TITLE
Missing some meta scopes to mark a whole block of something

### ISSUE THREAD

**Issue by aziz** [bathos/Ecmascript-Sublime#11]
This is a bit tricky to describe. But we need some meta scopes to mark the begining and end of things to be used by other packages, and not neccesarily color schemes. 
For example a meta scope for selecting all the function parameters or another meta scope to select the body definition of a funtion/class/object.
Did you get my idea?

**Comment by bathos** [comment]
Yup, we can add more of these -- but I think I need more specific knowledge of what we're trying to provide. Are these existing packages that look for specific meta scopes? If so, I'll need to know what the scope names they're looking for are.

**Comment by aziz** [comment]
No, it was just me thinking about writing a package to add more of those `Expand Selection to ...` in the selection menu for javascript. babel package does a relatively good job on this regard, lots of meta tags to denote the scope of code.
