### ISSUE TITLE
Static class property productions are not recognized

### ISSUE THREAD

**Issue by Daerzo** [bathos/Ecmascript-Sublime#14]
{_sorry for my bad English_}

Copy [this code](http://hastebin.com/raw/wevalutabi) (originally taken from [here](http://www.sitepoint.com/quick-tip-video-player-component-react/)) into your ST, and you'll see the problem with highlighting.

I'm a beginner, so I don't know whether the problem is in your package or in the syntax of the code itself.

**Comment by bathos** [comment]
Thanks, confirmed. I only added support for the class properties proposal a few weeks ago and apparently I left this out.
