### ISSUE TITLE
function expression not recognized when appearing as assignment value outside of declarations

### ISSUE THREAD

**Issue by aziz** [bathos/Ecmascript-Sublime#15]
``` js
var a = {}
a.onscroll = function() { 
  clearTimeout(seatmap.cartView.hideCartTimer); 
};
```

`function` does not have the proper scope
<img width="481" alt="screen shot 2016-05-16 at 14 47 10" src="https://cloud.githubusercontent.com/assets/3202/15290089/70f8603a-1b76-11e6-9215-67bbbd3c91aa.png">

**Comment by aziz** [comment]
found another one: 
<img width="999" alt="index_jsx_ _mnxweb" src="https://cloud.githubusercontent.com/assets/3202/16270339/3dfe8398-3896-11e6-8bf8-7d0b7c584cb4.png">

```js
var component = function (nextProps, nextState) {};
component.prototype = function (nextProps, nextState) {};
component.prototype.shouldComponentUpdate = function (nextProps, nextState) {};
```

**Comment by bathos** [comment]
This bug introduced when we added the function name scope to cases like `var x = function...`. It will currently happen in any situation where the LHS is not a declaration and the assignment value begins with `function`. Should be an easy fix, really, I just forgot about it!

**Comment by aziz** [comment]
This is not fixed for me. it still looks the same as what is shown in the screenshot

**Comment by bathos** [comment]
Oops, sorry, @aziz, I mistook this one for the problem with `foo = function() {}` — I’ll fix this one too when I get home from work.
