### ISSUE TITLE
Promise.resolve() breaks theme

### ISSUE THREAD

**Issue by barneycarroll** [bathos/Ecmascript-Sublime#17]
The closing parenthesis of `Promise.resolve()` is seen as a syntax error (providing an argument is fine).
![image](https://cloud.githubusercontent.com/assets/83627/17585245/90a00e1c-5fb2-11e6-849a-0bd419937094.png)

**Comment by bathos** [comment]
Fixed in 0.3.3.

**Comment by bathos** [comment]
@aziz this one is specifically because I was being excessively fancy with Promise itself even though it’s not really in the syntactic realm. I think I can just remove that handling and no one will miss it.
