### ISSUE TITLE
Sublime text crash

### ISSUE THREAD

**Issue by Grivel-l** [bathos/Ecmascript-Sublime#21]
Hi,
This plugin makes my Sublime text crash, when this syntax is active and I write something between my [ ], it often crashes.
For example I have:
`<MyElement style={[styles.myStyle, this.state.myElement.getLayout()]}>`
If I try to write a brace before `this.state.myElement.getLayout()` like this:
`<MyElement style={[styles.myStyle, {this.state.myElement.getLayout()]}>`
 my Sublime text crashes.

Sublime Text version: Build 3126
Thanks !

**Comment by thematho** [comment]
I have the same problem buth in different scenario, seems like Sublime Indexing is broken as well when trying to index the following scenario:
Using .es6 files:
`var foo = function () {/*...*/ };`
This doesn't happen when I name the anonymous function.
`var foo = function foo() {/*...*/ };`

**Comment by bathos** [comment]
Confirmed, it’s related to changes that went in two days ago. On it.

**Comment by bathos** [comment]
Fixed, Package Control should pick it up within the hour.

**Comment by Grivel-l** [comment]
Thank you for the quick fix !

**Comment by thematho** [comment]
Confirm It's fixed. However there is a little detail:
Using the same example [Plunker](https://plnkr.co/edit/a5kTag?p=catalogue)  there is a warning highlighting in the parenthesis of the anonymous function. Naming the function removes the warning.
