### ISSUE TITLE
ES proposal `export ... from ...` is marked as invalid

### ISSUE THREAD

**Issue by aziz** [bathos/Ecmascript-Sublime#22]
```js
export ModalHeader from './header';
export ModalFooter from './footer';
export ModalContent from './content';
```

![screen shot 2016-11-14 at 09 29 35](https://cloud.githubusercontent.com/assets/3202/20257920/10a4df4a-aa4d-11e6-8d40-f7fedc9634f9.png)

**Comment by bathos** [comment]
Changed the title because it’s actually not valid ES6 — rather this is a stage 1 proposal that Babel supports:

https://github.com/leebyron/ecmascript-export-default-from

I agree it’s a bug though, this is a transform a lot of people use.
