### ISSUE TITLE
Auto-indent not working for methods

### ISSUE THREAD

**Issue by stevenxxiu** [bathos/Ecmascript-Sublime#24]
Hi, great work and very happy with this package!

I have a small problem, when I type

    class A {
      a(){

and hit enter, sublime usually increases the indent, but in this package it is not. Any chance of fixing this? I haven't investigated it yet.

**Comment by bathos** [comment]
@aziz do you have any insights here? I fiddled with the indent rules and what I discovered was that they are seemingly just being ignored entirely. It didn’t matter what I put in there; I always got the same behavior. I’m guessing the metadata that associates it with the syntax definition might be borked somehow, but whatever is wrong, I’m not spotting it.

**Comment by bathos** [comment]
More context: I’m pretty sure this did work correctly at one time, and I’m not sure when it stopped.

**Comment by aziz** [comment]
I can't replicate this bug in my environment (Sublime 3125 on Mac)
Do you have the default `Javascript` syntax disabled?

could you give me more examples on how to trigger this indentation issue?
could you paste your settings regarding indentation in your `User/Preferences.sublime-settings`

**Comment by blake-regalia** [comment]
I am also getting this behavior 3126 on Mac. Nothing in debug log, user preferences normal.

```js
let f = () => {
	let g = () => { // hitting enter here does not auto-indent
};
```

**Comment by blake-regalia** [comment]
Confirmed. When I replace `decreaseIndentPattern` and `increaseIndentPattern` in `ecmascript-indent.tmPreferences` with the strings from [the JavaScriptNext](https://github.com/Benvie/JavaScriptNext.tmLanguage/blob/master/JavaScript%20Indent.tmPreferences) indent source, everything works as expected.
