### ISSUE TITLE
array destructuring not working with `this`

### ISSUE THREAD

**Issue by stevenxxiu** [bathos/Ecmascript-Sublime#25]
The following reports an error but is valid:

    [this.a, this.b] = [1, 2]

**Comment by bathos** [comment]
Noticed this recently, too. It’s true for the assignment targets in object destructuring, too  — should be an easy fix though.

**Comment by bathos** [comment]
Addressed in https://github.com/bathos/Ecmascript-Sublime/releases/tag/1.0.2

**Comment by stevenxxiu** [comment]
Awesome, thanks!
