### ISSUE TITLE
End of comment triggers auto-complete

### ISSUE THREAD

**Issue by stevenxxiu** [bathos/Ecmascript-Sublime#26]
If I type a new comment `// ` then it triggers auto-complete at the end, since it's marked as `meta.whitespace.es` instead of comment. Is there a way to disable this?

**Comment by bathos** [comment]
Ah, never noticed this. While it’s behaving "correctly" (`SingleLineCommentChar:: SourceCharacter but not LineTerminator`) it’s probably better for us to depart from that precision in this case and say the LF is part of `comment.line` anyway.

**Comment by bathos** [comment]
fixed in 1.0.4 (should have done them both at once, but I didn’t remember this until after the other fix)

**Comment by stevenxxiu** [comment]
thanks!
