### ISSUE TITLE
async delete()

### ISSUE THREAD

**Issue by stevenxxiu** [bathos/Ecmascript-Sublime#27]
The following is valid but shows an error. Delete is a common method for maps, sets, so it might be a common use case:

    class A {
      async delete(){

      }
    }

**Comment by stevenxxiu** [comment]
I'm not that familiar with `.sublime-syntax` but I think this patch works at line 3854:

        asyncMethod_AFTER_ASYNC:
          - match: '(({{identifierName}}))'

**Comment by bathos** [comment]
yep, that is the exact correction needed

**Comment by bathos** [comment]
Fixed in 1.0.3
