### ISSUE TITLE
Ternary statements edge case

### ISSUE THREAD

**Issue by barneycarroll** [bathos/Ecmascript-Sublime#29]
Given the ternary statement `a ? b : c`, syntax highlighting breaks down when `a` and `?` are on one line and there is a line break between `?` and `:`.

This is sometimes useful when `a` and `b` are short expressions but `c` is large.

***

Thanks so much for this wonderful package. The detail of token distinction is exceptional - there's nothing quite like it.

**Comment by barneycarroll** [comment]
There are other edge cases - it seems the general rule is that multiline ternary statements are problematic unless explicitly wrapped in parentheses.

**Comment by bathos** [comment]
Can you include an example of code that causes this? There’s nothing linebreak-sensitive about the production itself, so we should be able to get this correct 100% of the time. FWIW I normally break ternaries across lines myself and I’ve never seen the scopes for this miss, so I’m wondering if there could be some secondary factor about the internal expressions that might bork it.

**Comment by barneycarroll** [comment]
To be honest this came up on some very gnarly code that would fail any established lint styling exercise. I'll try and isolate it tomorrow morning.

**Comment by bathos** [comment]
@barneycarroll if isolating is a hassle, it’s cool to post some straight up gnarl

**Comment by bathos** [comment]
Gonna close this since I can’t repro and it’s been a few weeks — reopen if you turn something up.
