### ISSUE TITLE
I found a bug in "get" and "set" prefix for object

### ISSUE THREAD

**Issue by pucelle** [bathos/Ecmascript-Sublime#41]
Hi, I found codes like this can't be highlighted correctly:
`
{
    get () {
        ....
    },
    set () {
        ....
    }
}
`

**Comment by bathos** [comment]
Thank pucelle. I thought this was something that got fixed a while back, and when I test it I’m getting the right behavior:

<img width="414" alt="screen shot 2017-07-25 at 12 15 10 am" src="https://user-images.githubusercontent.com/6257356/28555497-59639c9c-70ce-11e7-9aa9-6182a7495662.png">

However it might be borked only in specific contexts. Can you provide a complete chunk which reproduces the problem?

**Comment by pucelle** [comment]
Hi, Bathos.
Sorry for reply you late.
Here is code that cant work with my sublime:`
Watcher.prototype = {
	get () {
		let oldDeps = this.deps
		let newDeps = this.deps = Object.create(null)

		runningWatcher = this
		let value = this.getter.call(this.vm[proxySymbol])
		runningWatcher = null

		for (let key in oldDeps) {
			let oldObserver = oldDeps[key]
			if (!newDeps[key]) {
				oldObserver.removeWatcher(key, this)
			}
		}

		return value
	},
	set (value) {
		let {vm, exp, writeVM, setter} = this

		if (!writeVM) {
			let firstProp = lexer.getFirstProperty(exp)
			writeVM = this.writeVM = this.findWriteVM(vm, firstProp)
		}

		if (!setter) {
			setter = this.setter = lexer.compileWritter(exp)
		}
		
		setter.call(vm, writeVM[proxySymbol], value)
	},
}`

**Comment by pucelle** [comment]
Here is the screenshot:
![get-set](https://user-images.githubusercontent.com/9691487/28761797-e0675962-75e3-11e7-9b66-e865678c2f59.png)

**Comment by bathos** [comment]
That appears to be a different syntax definition for JS, not ES sublime. The scoping throughout that screenshot is not consistent with this library.

**Comment by pucelle** [comment]
Hi, Bathos:
After checked my syntax config in Sublime, I did choose the "JavaScript" as syntax, not 'EcmaScript'.
Sorry for the trouble I made.
