### ISSUE TITLE
Static properties without semicolons break everything

### ISSUE THREAD

**Issue by are1000** [bathos/Ecmascript-Sublime#42]
Just like in the title.

![d85skl9](https://user-images.githubusercontent.com/3817785/29111057-2b770ad6-7ce9-11e7-9e6f-3f03586d4626.png)

**Comment by bathos** [comment]
At the time I introduced class fields here it did not yet have a formal grammar and it was unclear whether ASI would be applicable, so this choice was made intentionally. The formal grammar today does permit ASI however, despite the much higher chances of ambiguous sequences in class bodies, so I can give supporting it a go (with the caveat that ASI-like behavior in a pattern-based syntax def like this can only be approximated).
