### ISSUE TITLE
Arrow function as value of class instance field

### ISSUE THREAD

**Issue by spence** [bathos/Ecmascript-Sublime#43]
Seems like class methods using arrow functions are not supported?

<img src="https://user-images.githubusercontent.com/138762/29593496-8b189678-875f-11e7-85f3-1637e88e98aa.png" width=300 />

**Comment by bathos** [comment]
Can you explain more about what was expected? Since it looks like you’re using a theme that doesn’t have styles for most of the stuff in this syntax def, it’s hard to tell what isn’t working as expected there.

**Comment by bathos** [comment]
Oh hey there @dangh ! Looks like you figured out what this issue was asking for.

(Your flow work looks really great. Do you think it’s sensible to incorporate it here?)

**Comment by bathos** [comment]
Closed with 1.1.2, which pulls in the fix from @dangh’s fork.

**Comment by dangh** [comment]
Oh hey there @bathos, thanks for inviting me.

To be honest, I'm not fully understand sublime syntax and I'm not a Flow user myself. My fork is purely experimental and not ready to use atm. I still improving it  and will make pull request whenever I feel it's good enough 😄

Thank you so much for your js syntax. It's the best.

**Comment by bathos** [comment]
Thanks! It looks like it’s coming along great, so if you do get it to a spot where you think it’s ready I’d be happy to take it for a spin / review. Some of the stuff in your "personalize" branch seems like it would represent solid improvements for all users, too.
