### ISSUE TITLE
Need 2 semicolons to recover `static` keyword

### ISSUE THREAD

**Issue by dangh** [bathos/Ecmascript-Sublime#49]
As you can see in the screenshot. It used to work before [this commit](https://github.com/bathos/Ecmascript-Sublime/commit/35d74283d5c68134e178c609b28c338f8cba7375)

The first semicolon has scope `punctuation.terminator.property.es`.
The second semicolon has scope `punctuation.terminator.statement.es`.

<img width="167" alt="screen shot 2018-04-09 at 3 41 05 am" src="https://user-images.githubusercontent.com/1020347/38471739-f49906da-3ba7-11e8-9d16-c8edf05ff055.png">

**Comment by bathos** [comment]
Thanks, esp for including the scope info — there were a few problems with that overhaul, and I thought I’d fixed them all since then, but I forgot to check ASI recovery cases (this affected non-static as well).

Should be good in 1.6.2.
