### ISSUE TITLE
More specific scopes for `module.export` and  `exports` for node

### ISSUE THREAD

**Issue by aziz** [bathos/Ecmascript-Sublime#5]
I want to give these keywords a special color but I can't. the scope is a bit too generic.

**Comment by bathos** [comment]
the new scope is called `support.variable.node.module.es`. It covers:

- the identifier `module`
- the identifier `exports`
- the property `exports` when accessed on `module`

**Comment by bathos** [comment]
@aziz By the way, if you're working on a theme, please feel free to open a PR to add it to the package!

**Comment by aziz** [comment]
I've just updated my color scheme to support your awesome ES syntax. 
Here is the [code](https://github.com/aziz/sublimeText3-Userfiles/blob/master/Color%20Schemes/PlasticCodeWrap2.tmTheme) and you can [preview it here](https://tmtheme-editor.herokuapp.com/#!/editor/url/https://raw.githubusercontent.com/aziz/sublimeText3-Userfiles/master/Color%20Schemes/PlasticCodeWrap2.tmTheme)
