### ISSUE TITLE
"Apparent recursion within a with_prototype action: 25000 context sanity limit hit"

### ISSUE THREAD

**Issue by bathos** [bathos/Ecmascript-Sublime#51]
Unsure if this is a Sublime issue or an issue introduced in the last release, but presently the syntax def is unloadable for me.

**Comment by blake-regalia** [comment]
I'm not getting this on my end. Does this happen no matter the file contents or only when using nested syntaxes (i presume that's why it's complaining about `with_prototype`)? If so, could you post a snippet that is causing this? Which version of Sublime?

**Comment by rafapaulin** [comment]
Same problem here... using latest sublime build..

Tried commenting the line @blake-regalia mentioned, but it dit no fix =(

**Comment by blake-regalia** [comment]
@rafapaulin Did you only comment out that line or the whole rule? I should have highlighted the range, try commenting out these 5 lines: https://github.com/bathos/Ecmascript-Sublime/blob/e203d3aa7bbc644704f66c7aaa3e62c24549c9c3/ecmascript.sublime-syntax#L5528-L5532

**Comment by blake-regalia** [comment]
I have another hunch. It's possible that the Sublime devs thought of making `push/set` native syntax defs automatically use the new `embed` feature, which would be problematic for the nested JavaScript rule because it would recursively load the current default JavaScript syntax, which would be our Ecmascript syntax def. This would certainly be a Sublime bug and not a feature. If this is the case and if commenting out these lines solves the issue, it would be a good indication of whats causing it:

https://github.com/bathos/Ecmascript-Sublime/blob/e203d3aa7bbc644704f66c7aaa3e62c24549c9c3/ecmascript.sublime-syntax#L5687-L5698

**Comment by rafapaulin** [comment]
@blake-regalia tried to comment out both ranges you suggested, appart from each other and together... still did not fix =(

**Comment by rafapaulin** [comment]
I may share my sublime license with you if you need

**Comment by bathos** [comment]
I don’t know much about the new nesting stuff — am I understanding correctly that it is a breaking change in Sublime? Like, is it even possible to have the nested syntaxes working in both current Sublime 3 and the dev build?

**Comment by blake-regalia** [comment]
@bathos it *should not be* a breaking change, and could have just been a bug in 3166 -- looking at the current dev build changelogs seems like there were some crash issues w 3166, does this still happen in the most recent build?

**Comment by bathos** [comment]
3167 and 3168 still exhibit the same behavior (sorry I haven’t been able to experiment with this properly myself yet, just been busy w/ work)

**Comment by bathos** [comment]
3170 is now stable and released, so I believe this now this affects all users, womp. Gonna look into it tonight.

**Comment by bathos** [comment]
Confirmed that it’s related to nested syntax by fully disabling them — gonna try to re-enable bit-by-bit to see when it freaks out.

**Comment by bathos** [comment]
...it’s the markdown one :o

**Comment by bathos** [comment]
I published the easy fix (disabling nested markdown) till we can figure out why this happens. There’s nothing obvious to me; it seems like it’s got to be something unique about the Markdown syntax definition triggering it.

**Comment by blake-regalia** [comment]
This is most certainly caused by https://github.com/sublimehq/Packages/blob/master/Markdown/Markdown.sublime-syntax#L993 which loads contexts from Ecmascript, which then includes contexts from Markdown, when then loads contexts from Ecmascript, which then includes contexts from Markdown, .... at least, that is my suspicion: https://github.com/SublimeTextIssues/Core/issues/2252

I will see if switching to `embed` will fix this. Btw, can our releases target specific builds of Sublime?

**Comment by bathos** [comment]
> Btw, can our releases target specific builds of Sublime?

I think/thought this is possible, but I’m not sure what the correct way to do it is. The registry repo is [Package Control Channel](https://github.com/wbond/package_control_channel), where you’ll see [our entry](https://github.com/wbond/package_control_channel/blob/master/repository/e.json#L186-L196) complete with the typo `ES2105` haha:

```json
{
  "name": "Ecmascript Syntax",
  "details": "https://github.com/bathos/Ecmascript-Sublime",
  "labels": [ "Javascript", "ES6", "ES2105" ],
  "releases": [
    {
      "sublime_text": ">=3084",
      "tags": true
    }
  ]
},
```

In the releases array, `sublime_text` can associate an entry with a sublime version range. In this case it’s indicating that it should be available only for 3084 (the version that introduced sublime-syntax) and later, and `tags: true` means that Package Control should look for semver git tags and treat them as releases.

If you look around at other entries, you’ll see that many specify a `branch` instead of `tags`. This seems like what we’d be looking for, but there’s [a catch](https://packagecontrol.io/docs/submitting_a_package#Step_4):

> Please note that branch-based releases have been deprecated and no new packages will be accepted that utilize that feature. Existing packages are encouraged to update to using tags.

So we can’t use the `branch` option, which leaves me uncertain what one is supposed to have different releases associated with sublime version ranges. I don’t see any mention of this in the Package Control docs so far.

https://github.com/wbond/package_control_channel/blob/master/repository/e.json#L126-L133

**Comment by bathos** [comment]
I think I found an example that does it with tags — apparently it can [specify a prefix](https://github.com/wbond/package_control_channel/blob/master/repository/c.json#L855-L870):

```json
{
  "name": "ChineseLocalizations",
  "previous_names": ["ChineseLocalization"],
  "details": "https://github.com/rexdf/ChineseLocalization",
  "labels": ["localization", "chinese", "中文", "japanese", "日本語"],
  "releases": [
    {
      "sublime_text": "<3000",
      "tags": "st2-"
    },
    {
      "sublime_text": ">=3000",
      "tags": "st3-"
    }
  ]
},
```

**Comment by blake-regalia** [comment]
Interesting, it looks like you can also use `"tags": true` for the default/latest build and optionally use a prefix for others, [for example:](https://github.com/wbond/package_control_channel/blob/master/repository/e.json#L1524-L1533)

```json
"releases": [
	{
		"sublime_text": "<3000",
		"branch": "st2"
	},
	{
		"sublime_text": ">=3000",
		"tags": true
	}
]
```

**Comment by bathos** [comment]
That example is tags vs branch. I didn’t see any with tags unprefixed + tags prefixed, but I didn’t search for very long so I dunno. (I’m surprised that I couldn’t find any of this documented — I might just be missing it?)

**Comment by blake-regalia** [comment]
Found it: 
```
// If your package is only compatible with specific builds of
// Sublime Text, this will cause the package to be hidden from
// users with incompatible versions.
//
// The "tags" key can be true for all valid semantic version tags, or
// can be a prefix string. Only tags in the form
// {prefix}{semantic_version} will be selected. In the example below,
// the entry with "sublime_text": "<3000" will match tags like:
//
// "st2-1.0.0"
// "st2-1.1.0"
//
// The release with "sublime_text": ">=3000" will match tags like:
//
// "st3-1.0.0"
// "st3-1.1.0"
{
	"details": "https://github.com/wbond/sublime_alignment",
	"releases": [
		{
			"sublime_text": "<3000",
			"tags": "st2-"
		},
		{
			"sublime_text": ">=3000",
			"tags": "st3-"
		}
	]
},
```

It's in their [example-repository.json](https://raw.githubusercontent.com/wbond/package_control/master/example-repository.json).

**Comment by bathos** [comment]
I’m told this has begun again. My guess is that it was triggered indirectly by changes in one of the delegated syntaxes, though I won’t be able to check which till later :/

**Comment by blake-regalia** [comment]
Can anyone share a snippet that causes this? Also what version of Sublime? I'm running build 3176 and am not able to get any errors.

**Comment by bathos** [comment]
I’ll try to get some more info. Two people messaged me directly about it today. My impression was that, as before, no file even needs to be open — it just happens from the extension existing at all.

**Comment by blake-regalia** [comment]
Hmm... just looked through all the latest [base syntax](https://github.com/sublimehq/Packages/tree/master) package commits that might affect this and found: CSS, SQL, and ShellScript syntaxes changed in last few weeks, the only suspicious commit being for bash at this line here: https://github.com/sublimehq/Packages/commit/4cfa7b9c37a54c84031d7b165ce1e5a888b94da6#diff-fe682d41416db7dad26aa8c60e0dc02eR300 so I cloned it and tested, but no problems. I'll wait for more info.

**Comment by acconrad** [comment]
Hi there! So I was one of those two people to message about this. I have the Ecmascript syntax installed on ST3.1.1 build 3176.

Steps to reproduce: 

1. Open SublimeText. It will blow up only one
2. Open a repo with both `.md` and `.js` files where the default syntax for `.md` is `Markdown` and the default syntax for `.js` is `Ecmascript`
3. Open a readme or javascript file
4. The following popup is shown:

<img width="598" alt="screen shot 2018-07-25 at 4 34 21 pm" src="https://user-images.githubusercontent.com/422184/43226024-2cf4ecaa-904a-11e8-8dfa-caf365e42331.png">

Another example I caught while opening a JS file:

<img width="607" alt="screen shot 2018-07-25 at 10 37 32 am" src="https://user-images.githubusercontent.com/422184/43226034-372b36fc-904a-11e8-90c4-438e8dfd8820.png">

**Comment by blake-regalia** [comment]
Thanks @acconrad , can you please confirm which version of the "Ecmascript Syntax" package you have installed? Ctrl+Shift+P > "Package Control: List Packages" > "Ecmascript Syntax".

**Comment by acconrad** [comment]
<img width="598" alt="screen shot 2018-07-25 at 9 47 51 pm" src="https://user-images.githubusercontent.com/422184/43236669-f0b6fb4e-9075-11e8-8e1a-f532ad47799c.png">

Looks like I'm on the same version as you

**Comment by blake-regalia** [comment]
This is a tricky one -- not sure what's causing it but I went ahead and published a release that might fix it. Please restart Sublime, check that it updates Ecmascript Syntax to v1.6.7 and then see if the problem still exists.

**Comment by blake-regalia** [comment]
Hmm - I'm still unable to reproduce this no matter what I try, but I have some ideas about diagnosis, @acconrad . This should help us narrow it down:

1. Remove the Ecmascript Syntax package via Package Control.
2. Open the user preferences directory, Sublime Text > Preferences > Browse Packages ... "User". _Do you have an "ecmascript.sublime-settings" file here? What about a "Markdown.sublime-settings" or any other relevant files? Please let me know if you do._ And if you do, move them away from this directory temporarily.
3. Restart Sublime.
4. Open a Markdown `.md` file. There should be no errors at this point, if there are -- _something else is up_.
5. Copy this code-fenced section into the markdown file:
````md
```js
call();
```
````
6. Put your caret on the `call` text and Ctrl+Shift+P  (oops, last time I said this I meant Cmd+Shift+P,  this time i really mean **Ctrl**). _Screenshot/copy the scopes that list under the caret and post it here._
7. With the Markdown file still open, change the syntax association by going View > Syntax > Open all with current extension as ... > Plain Text.
8. Install the Ecmascript Syntax via Package Control.
9. Open a JavaScript `.js` file.  _What happens?_
10. If you get to this step and you haven't encountered any errors yet, try changing the Markdown association back by opening an `.md` file and opening all with current extension as Markdown>Markdown.

**Comment by acconrad** [comment]
@blake-regalia It did blow up on Step 4. I followed it to the tee, _but_ I only had a `ecmascript.sublime-settings` file in that `User/` folder but _not_ a `Markdown.sublime-settings`, so what's next?

**Comment by blake-regalia** [comment]
Interesting... What are the errors you got? Could you post a screenshot?

**Comment by blake-regalia** [comment]
Btw @acconrad for our own sanity, and to get you coding again in the meantime, I created a branch without nested syntax support. Here's how you can install it:

```bash
cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/
git clone -b safe-mode https://github.com/bathos/Ecmascript-Sublime ecmascript
```

Then, View > Syntax > Open all with current extension as... > User > Ecmascript

**Comment by bathos** [comment]
Thanks for going deep on this blake, it’s very appreciated. I haven’t been able to repro either unfortunately.

**Comment by blake-regalia** [comment]
@bathos I figured this out. Oddly enough, it appears that ST 3176 may or may not (depending on your OS it seems) load the Ecmascript syntax as the default `scope:source.js`, such as when the [base HTML syntax](https://github.com/sublimehq/Packages/blob/master/HTML/HTML.sublime-syntax#L612) embeds javascript. However, if I change our root scope from `source.js source.es` to just `source.js`, then indeed the Markdown and HTML base syntaxes will start using Ecmascript syntax for embedded js if they weren't already. This inevitably causes the errors @acconrad is reporting here.

I'm going to disable the affected nested syntaxes for now: DOT and HTML. Unfortunately, it seems that we cannot nest any syntax that ultimately embeds or pushes a `source:js` to the stack, (e.g., we nest DOT, DOT pushes HTML, HTML pushes JS, stack blows up). Really a poor oversight by the ST3 team if you ask me  :/

As a remedy, I'm going to look into _generating_ a compatible HTML, DOT, and Markdown syntax directly from the base syntaxes. That way we can just ship our own "safe" nested syntaxes.

**Comment by acconrad** [comment]
@blake-regalia you are awesome, thank you for diving into this!

**Comment by blake-regalia** [comment]
@bathos I drafted a release for 1.7.0, but want to make sure it doesn't break anything else incidentally. Could you update your local repo and check that everything looks good?

**Comment by blake-regalia** [comment]
Released [1.7.0](https://github.com/bathos/Ecmascript-Sublime/releases/tag/1.7.0)

**Comment by bathos** [comment]
Sorry I missed that last request @blake-regalia ... but wow! This is a crazy impressive update (and everything seems to be fine).

**Comment by bathos** [comment]
May have spoken too soon. I’ve seen no highlighting issues, but it seems that shortcuts for commenting out lines (both single and multi) have stopped working. If you can confirm (not 100% sure ES Sublime is the cause yet) I’ll open a new issue.

**Comment by blake-regalia** [comment]
Hmm I can't seem to reproduce this yet. I just noticed some old scopes on a few .tmPreferences files and patched them real quick, see if that did anything?

**Comment by bathos** [comment]
This was fixed by the new release! Thanks again. 🙇
