### ISSUE TITLE
HTML highlighting not working

### ISSUE THREAD

**Issue by naoki-s** [bathos/Ecmascript-Sublime#53]
If I use the block comment directive for HTML (`/* syntax: html */`), anything following it appears like a comment. The directive for XML (`/* syntax: xml */`) works properly though.

(ver. 1.6.8; Sublime Text 3.1.1, Build 3176; macOS 10.13.6)

**Comment by blake-regalia** [comment]
Fixed in [1.7.0](https://github.com/bathos/Ecmascript-Sublime/releases/tag/1.7.0)
