### ISSUE TITLE
Consider bring back source.js scope

### ISSUE THREAD

**Issue by dangh** [bathos/Ecmascript-Sublime#54]
I just notice today that my snippets stop working because the top level scope changed from `source.js source.es` to `source.es` only.

I think there's lot of packages only support `source.js` since it's come with the default syntax. Should we bring it back?

**Comment by blake-regalia** [comment]
Ahhh -- sorry guys, this was my mistake. I just patched a fix and will release shortly. I suspect this might have been related to the issue @bathos was having. I'll explain the problem in more detail in the release.

**Comment by blake-regalia** [comment]
@dangh can you let me know if [this](https://github.com/bathos/Ecmascript-Sublime/releases/tag/1.7.1) fixes the issue?

**Comment by dangh** [comment]
@blake-regalia It's working now. Thanks for the fix.
