### ISSUE TITLE
a way of setting the default syntax for a template tag

### ISSUE THREAD

**Issue by Janpot** [bathos/Ecmascript-Sublime#57]
right now you can do
```js
const escapeHtml = require('escape-html-template-tag');
const myTitle = /* syntax: html */ escapeHtml`<title>hello world</title>`;
const myHtml = /* syntax: html */ escapeHtml`
<html>
  <head>${myTitle}</head>
</html>
`;
```
Which is extremely helpful.  But it also requires me to write 
```js
/* syntax: html */ escapeHtml`
```
everywhere.
Would it be possible to somewhere in the file "bind" the syntax with the template tag so it will be applied automatically everywhere it is used? i.e.
```js
 /* syntax(escapeHtml): html */
const escapeHtml = require('escape-html-template-tag');
const myTitle = escapeHtml`<title>hello world</title>`;
const myHtml = escapeHtml`
<html>
  <head>${myTitle}</head>
</html>
`;
```

Edit:

Or maybe something like:

```js
 /* syntax escapeHtml: html, graphql: graphql */
```

**Comment by blake-regalia** [comment]
Unfortunately, this can't be done with syntax definitions -- but a similar effect could be achieved with a snippet, i.e., one that automatically inserts the `/* syntax: html */` comment for you, even including the `escapeHtml` part too. Perhaps if you can define how to trigger something like that then we can add a snippet to do make a shortcut for it.

**Comment by Janpot** [comment]
snippets don't feel like the right solution for me either. nevermind, I guess it was a long shot anyway.
