### ISSUE TITLE
Comma background in destructuring assignments

### ISSUE THREAD

**Issue by Janpot** [bathos/Ecmascript-Sublime#59]
Something seems to be a bit off on the commas when I destructure multiple values
![screen shot 2018-09-19 at 12 41 24](https://user-images.githubusercontent.com/2109932/45748623-95473700-bc09-11e8-9450-cd216edb1161.png)

**Comment by bathos** [comment]
@Janpot the choices of what coloring to apply to scopes comes from themes rather than the syntax definition. ES Sublime comes bundled with some themes, but that’s not one of them.

**Comment by Janpot** [comment]
You're right. Been using spacegray for years without a problem. Looks like current versions of sublime support default themes/color schemes that align better with my preferences. Thanks.

**Comment by blake-regalia** [comment]
@Janpot if you're using nested syntax directives then I'd recommend checking out the `excelsior` Ecmascript theme.  Cmd+Shift+P > UI: Select Color Scheme > excelsior

**Comment by Janpot** [comment]
Thanks. I've always been using
https://github.com/kkga/spacegray/blob/master/base16-ocean.dark.tmTheme
For now the Mariana default color scheme seems to hurt my eyes the least. I don't think I'm ready to go with excelsior yet.

**Comment by bathos** [comment]
I would love to get some 'es-sublime enhanced' versions of common schemes in here at some point, though I’m not exactly the greatest at that stuff.
