### ISSUE TITLE
Lacking root scope of  `souce.js` breaks a lot of other packages

### ISSUE THREAD

**Issue by aziz** [bathos/Ecmascript-Sublime#6]
I'm wondering why you've decided to change the root scope from `souce.js` to `source.es`
This cause a lot of other packages of mine to break. Things from auto completion to ES6 compiler.
Isn't it possible to stick with `source.js` and just extend the more specific scopes. 
Something like  `source.js  variable.parameter.es` instead of `source.es variable.parameter.es`

**Comment by bathos** [comment]
This was done mainly to distinguish the 'interoperability scopes' that let other themes still work more or less correctly with ES Sublime from the 'native' stuff. All the packages I've dealt with work off extensions, I guess, so I wasn't aware that there were non-highlighting-related packages hooking into the highlighting scopes to do stuff. I'll look into adding source.js as either a second common ancestor scope or the only common ancestor scope and see if it doesn't break things -- could you give me a specific example plugin I should test it against?

**Comment by aziz** [comment]
Most snippet packages are not working, I use:
- JavaScript & NodeJS Snippets 
- React ES6 Snippets           
- ES6-Toolkit                  

I managed to change the settings for some other packages to make them work but it's still really annoying since packages are not working out of the box. I got these working so for: 

- SublimeLinter-contrib-eslint
- AngularJS

**Comment by aziz** [comment]
Everything about this package is awesome except this decision of yours to change the root scope! It breaks so many packages and causes so much pain. Why not keeping the `source.js` as the root but immediately adding `source es` after that.

**Comment by bathos** [comment]
Added with 0.3. Let me know if that fails to fix it; I included both at the root, which I think should be fine, but I didn't test it admittedly.

**Comment by aziz** [comment]
seems to fix all my problems. Thanks again for making this awesome package.  Javascript is going through a lot of changes packages like this need constant maintenance and attention.
