### ISSUE TITLE
Update repository description

### ISSUE THREAD

**Issue by blake-regalia** [bathos/Ecmascript-Sublime#61]
Would it be nice to clarify that the syntax actually supports ES2018(9?) and/or Stage 4 proposals?

**Comment by bathos** [comment]
It gets pulled in by Package Control as the package description, right?

I thought about adding more keywords last time I updated the Package Control entry but was reluctant to be comprehensive for fear of it being spammy. Expanding the repo desc is a good idea, probably the more kosher way to make it discoverable / clarify its purpose.

**Comment by blake-regalia** [comment]
@bathos 

> It seems wise to keep the final qualifier there

Agreed - "absurdly specific scopes" is succinct and catchy!

> we should probably drop "Sublime" since it’s redundant

Good point, although it probably helps discoverability when searching the web. Then again, "Sublime" is also in the name of the package.

Something else to consider is that PackageControl (or ST3?) is cutting text from the description line if it is too wide for the command palette modal.
<img width="605" alt="screen shot 2018-10-20 at 9 51 38 pm" src="https://user-images.githubusercontent.com/1456400/47263291-afe42880-d4b3-11e8-9216-76d5a6802f1c.png">
<img width="605" alt="screen shot 2018-10-20 at 9 57 01 pm" src="https://user-images.githubusercontent.com/1456400/47263292-afe42880-d4b3-11e8-9cb8-0f7a47d58d0e.png">

This probably varies slightly platform to platform, but if it's too long then words are removed starting from the middle. Although, **the descriptions are not searchable** from the command palette anyway.

Based on some back-of-the-pixel font metrics I just did, if you truncate what you suggest by just removing the word "definition", then it fits the modal width:

> ECMAScript/JavaScript syntax (ES2015-ES2018, JSX, template highlighting, etc) with absurdly specific scopes

**Comment by bathos** [comment]
LGTM — updated it. Unsure if Package Control will pick that up automatically or if it only “takes” when it detects a new release.
