### ISSUE TITLE
styled jsx has no css autocomplete and emmet does not work

### ISSUE THREAD

**Issue by nhooyr** [bathos/Ecmascript-Sublime#67]
Title.

The autocomplete doesn't' autocomplete css, it's just the generic autocomplete and emmet also does not work.

**Comment by nhooyr** [comment]
Oddly enough, if you put a period first, autocomplete works:

<img width="1274" alt="Screen Shot 2019-05-10 at 7 07 22 PM" src="https://user-images.githubusercontent.com/10180857/57560889-d89c1480-7356-11e9-830e-a8b96e2d1bd7.png">

Not sure what's going on.

**Comment by nhooyr** [comment]
Emmet thinks the CSS is JSX.

Also, the scope for the CSS selectors is property-value for some reason.

<img width="1274" alt="Screen Shot 2019-05-10 at 7 11 07 PM" src="https://user-images.githubusercontent.com/10180857/57560998-637d0f00-7357-11e9-8762-88a0dbb63672.png">

**Comment by nhooyr** [comment]
The `/* syntax: css */` makes everything work properly again aside from emmet.

**Comment by bathos** [comment]
This is related to the fact that the autodetected styled jsx and css tags without a syntax directive do not delegate to the default sublime css definition, which borks easily when there are interpolated values in the CSS. (We might be able to fix it by tweaking the root scopes that uses, not sure.)

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
