### ISSUE TITLE
Use a package setting to override the block comment directive syntax

### ISSUE THREAD

**Issue by joshfester** [bathos/Ecmascript-Sublime#69]
It would be very useful if it were possible to use a package setting to change the block comment syntax from `syntax: {SYNTAX_NAME}` to something else. I'm working with a team that uses other editors like VSCode and Atom. Those editors have similar plugins, but use a different syntax. If this setting were available, we could have a unified syntax for the entire team without worrying about what their favorite text editor is 🙂

**Comment by bathos** [comment]
AFAIK, doing this would require generating new versions of the syntax definition dynamically in response to settings changes, implying a runtime component to this plugin that doesn’t currently exist. My guess is that it would be possible. Maybe there’s some prior art out there for this?

@blake-regalia is that correct, or do you know of other mechanisms by which user variables could be used in sublime syntax definitions?

**Comment by blake-regalia** [comment]
Not feasible. Syntax definitions currently have to be static in Sublime Text other than the way @bathos describes.

@joshfester i'd be curious to know how do the other editors/plugins use such directives? Keep in mind that we also support highlighting triggered by a few template tags such as `html` and `css` (which we should probably document).

**Comment by joshfester** [comment]
@blake-regalia it seems like most of them use `/* {SYNTAX_NAME} */`. However, I believe template tags would also be a great solution. I was not aware there was support for that!

**Comment by bathos** [comment]
It seems reasonable to me to make the `syntax:` prefix optional. If that aligns with how others are doing this, it’s definitely a lot simpler than adding a runtime thingie for generating (and then managing?) custom definitions.

**Comment by joshfester** [comment]
That would be perfect!

**Comment by blake-regalia** [comment]
@joshfester [see 2.4.0](https://github.com/bathos/Ecmascript-Sublime/releases/tag/2.4.0).

I'm going to close this issue for now but I am still interested in dynamic or user-generated nested syntax capabilities. Feel free to open a new issue for that if you'd like.
