### ISSUE TITLE
Support JSX 

### ISSUE THREAD

**Issue by aziz** [bathos/Ecmascript-Sublime#7]
I'm quite use to your awesome syntax for javascript and I hate it that I need to switch to Babel Javascript to edit react jsx files. It would be nice to support JSX since react is becoming more and more popular.

**Comment by bathos** [comment]
I think that does it. I only added colors for it in Excelsior -- probably not the best ones, either -- feel free to open a PR if you can make it prettier.

**Comment by aziz** [comment]
:+1:  awesome
