### ISSUE TITLE
LSP integration

### ISSUE THREAD

**Issue by ryanpcmcquen** [bathos/Ecmascript-Sublime#86]
If I want to use the Naomi syntax package with LSP, I use a setting like this for the `LSP-typescript` package:

```
// Settings in here override those in "LSP-typescript/LSP-typescript.sublime-settings"
{
    "languages": [
        {
            "languageId": "javascript",
            "scopes": ["source.js"],
            "syntaxes": [
                "Packages/JavaScript/JavaScript.sublime-syntax",
                "Packages/Babel/JavaScript (Babel).sublime-syntax",
                "Packages/Naomi/syntaxes/naomi.fjsx15.sublime-syntax"
            ]
        },
        {
            "languageId": "javascriptreact",
            "scopes": ["source.jsx"],
            "syntaxes": [
                "Packages/User/JS Custom/Syntaxes/React.sublime-syntax",
                "Packages/Naomi/syntaxes/naomi.fjsx15.sublime-syntax"
            ]
        }
    ]
}
```

Where are the syntaxes stored for Ecmascript? I can't find them anywhere in the Sublime `Packages` directory.

**Comment by blake-regalia** [comment]
Okay, maybe I misunderstood the initial question my apologies @ryanpcmcquen . If you installed Ecmascript from PackageControl the main syntax will be at `"Packages/Ecmascript/ecmascript.sublime-syntax"` . The contents of the .sublime-package installed from PackageControl is just a zip of the root source code directory in this repo.

**Comment by ryanpcmcquen** [comment]
Thank you @blake-regalia, I'll try that and report back.
