### ISSUE TITLE
Support for ES Class Fields & Static Properties

### ISSUE THREAD

**Issue by aziz** [bathos/Ecmascript-Sublime#9]
https://github.com/jeffmo/es-class-fields-and-static-properties
<img width="513" alt="screen shot 2016-02-10 at 12 55 18 am" src="https://cloud.githubusercontent.com/assets/3202/12934722/fdccc712-cf90-11e5-9d61-3c19f1ad23c7.png">

**Comment by bathos** [comment]
I still don't like them, but okay :)

**Comment by bathos** [comment]
Here are the three new scopes. I've also updated the Excelsior theme to take them into account.

`x = 3;`

- `x`: variable.other.readwrite.property.class
- `=`: punctuation.separator.key-value (it isn't the assignment operator, here)
- `;`: punctuation.terminator.property (it isn't the statement terminator, here)
